tom = Zombie.new(username: "tom_the_zombie", password: "brains")
tom.create_tweet(content: "I ate some brains. They were tasty.")
sleep(1)
ann = Zombie.new(username: "zombieann", password: "brains")
ann.create_tweet(content: "Will work for brains")
sleep(1)
tom.create_tweet(content: "Oh look! More brains! om nom nom...")
sleep(1)
ann.create_tweet(content: "On second thought, kidneys sound better")
bill = Zombie.new(username: "brains4lyfe", password: "brains")
bill.create_tweet(content: "Dude, where can I find the tastiest brains?", location: "Wal-mart")
sleep(1)
bob = Zombie.new(username: "hobbling_bob", password: "brains")
bob.create_tweet(content: "Anyone seen my foot?")
sleep(1)
mary = Zombie.new(username: "i<3brains", password: "brains")
mary.create_tweet(content: "Brains are gross! I like hearts much better.")
sleep(1)
sara = Zombie.new(username: "one_armed_sara", password: "brains")
mary.create_tweet(content: "I'm going downtown to get a snack. Anyone want to join me?")
sara.create_tweet(content: "Anyone know any good voice-recognition apps?", location: "Home")
sleep(1)
bob.create_tweet(content: "Nevermind. I found it! Anyone got some duct tape?")



tom = Zombie.new(username: "tom_the_zombie", password: "brains")
tweet1 = tom.create_tweet(content: "I ate some brains. They were tasty.")
tweet2 = tom.create_tweet(content: "Oh look! More brains! om nom nom...")
